name: Ruby

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['2.6', '2.7', '3.0', '3.1', '3.2']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Update the RubyGems system software
        run: gem update --system

      - name: Update Bundler
        run: bundle update --bundler

      - name: Install dependencies
        run: bundle install
